/**
 * Regenerates the skill's package dependency graph from package metadata.
 *
 * The retired MCP shipped a dependency-graph document that was generated by its
 * own build script. To avoid copying generated output, the skill generator
 * rebuilds the graph here from each package's `package.json` dependencies. The
 * result is deterministic and carries the generated-file marker, so the drift
 * gate keeps it current.
 *
 * @module skill/architecture
 */

import fs from 'node:fs';
import path from 'node:path';

import { GENERATED_MARKER, SkillGenerationError } from './mapping.js';

/**
 * Reads the internal (`@blendsdk/*`) dependencies of one package.
 *
 * Both `dependencies` and `peerDependencies` are included. Peer dependencies
 * matter for the reverse table ("if I change this package, what else might be
 * affected?"): the WebAFX plugins peer-depend on `webafx` and would otherwise
 * disappear from the graph.
 *
 * @param rootDir - Absolute path to the monorepo root
 * @param packageName - Short package name
 * @returns Sorted short names of the internal packages it depends on
 * @throws SkillGenerationError when the package manifest cannot be read or parsed
 */
function readInternalDependencies(rootDir: string, packageName: string): string[] {
  const manifestPath = path.join(rootDir, 'packages', packageName, 'package.json');

  let parsed: unknown;
  try {
    parsed = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'));
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    throw new SkillGenerationError(`Cannot read ${manifestPath}: ${reason}`);
  }

  if (typeof parsed !== 'object' || parsed === null) {
    return [];
  }

  const internal = new Set<string>();

  for (const field of ['dependencies', 'peerDependencies'] as const) {
    if (!(field in parsed)) {
      continue;
    }

    const entries = (parsed as Record<string, unknown>)[field];
    if (typeof entries !== 'object' || entries === null) {
      continue;
    }

    for (const dependency of Object.keys(entries)) {
      if (dependency.startsWith('@blendsdk/')) {
        internal.add(dependency.slice('@blendsdk/'.length));
      }
    }
  }

  return [...internal].sort();
}

/**
 * Builds the generated dependency-graph reference.
 *
 * The document shows a layered visual overview, the forward dependency list,
 * and the reverse dependency list. Output is byte-reproducible: packages keep
 * the sorted order they are passed in.
 *
 * @param rootDir - Absolute path to the monorepo root
 * @param packageNames - Sorted short names of the documented packages
 * @returns The complete dependency-graph reference content
 */
export function generateDependencyGraph(rootDir: string, packageNames: string[]): string {
  const graph = new Map<string, string[]>();

  for (const packageName of packageNames) {
    graph.set(packageName, readInternalDependencies(rootDir, packageName));
  }

  const dependsOn = (packageName: string): string[] => graph.get(packageName) ?? [];

  const lines: string[] = [
    '# Dependency Graph',
    '',
    '> Internal dependency relationships between BlendSDK packages.',
    '',
    '## Visual Overview',
    '',
    '```',
  ];

  const foundation = packageNames.filter(name => dependsOn(name).length === 0);
  const midLevel = packageNames.filter(name => {
    const count = dependsOn(name).length;
    return count >= 1 && count <= 2;
  });
  const highLevel = packageNames.filter(name => dependsOn(name).length >= 3);

  lines.push('Foundation (zero internal deps):');
  for (const packageName of foundation) {
    lines.push(`  ${packageName}`);
  }

  lines.push('', 'Mid-level (1-2 internal deps):');
  for (const packageName of midLevel) {
    lines.push(`  ${packageName} -> ${dependsOn(packageName).join(', ')}`);
  }

  lines.push('', 'High-level (3+ internal deps):');
  for (const packageName of highLevel) {
    lines.push(`  ${packageName} -> ${dependsOn(packageName).join(', ')}`);
  }

  lines.push(
    '```',
    '',
    '## Dependency List',
    '',
    '| Package | Depends On |',
    '|---------|------------|'
  );

  for (const packageName of packageNames) {
    const dependencies = dependsOn(packageName);
    const cell =
      dependencies.length > 0 ? dependencies.map(name => `\`${name}\``).join(', ') : '*(none)*';
    lines.push(`| ${packageName} | ${cell} |`);
  }

  lines.push(
    '',
    '## Reverse Dependencies',
    '',
    '> "If I change package X, what else might be affected?"',
    '',
    '| Package | Used By |',
    '|---------|---------|'
  );

  for (const packageName of packageNames) {
    const usedBy = packageNames.filter(candidate => dependsOn(candidate).includes(packageName));
    const cell = usedBy.length > 0 ? usedBy.map(name => `\`${name}\``).join(', ') : '*(none)*';
    lines.push(`| ${packageName} | ${cell} |`);
  }

  lines.push('', GENERATED_MARKER, '');

  return lines.join('\n');
}
