/**
 * Source-to-destination mapping for the BlendSDK agent skill.
 *
 * The skill's package references are assembled from the per-package
 * `ai-training/` markdown files. This module owns the fixed mapping between
 * those source files and the five focused reference files the skill exposes,
 * and rejects source paths that would escape the package directory.
 *
 * @module skill/mapping
 */

import fs from 'node:fs';
import path from 'node:path';

/**
 * Marker appended as the final line of every generated file.
 *
 * The marker distinguishes files the generator owns from hand-written or
 * migrated content. The drift gate uses it to decide which files to compare, so
 * it must appear verbatim.
 */
export const GENERATED_MARKER =
  '<!-- Generated by scripts/skill/generate.ts — do not edit by hand. -->';

/**
 * Error raised when skill generation cannot proceed safely.
 *
 * Callers treat any instance as a fatal, fail-closed condition: the generator
 * stops before writing partial output.
 */
export class SkillGenerationError extends Error {
  /**
   * @param message - Human-readable description of the failure
   */
  constructor(message: string) {
    super(message);
    this.name = 'SkillGenerationError';
  }
}

/**
 * One destination reference and the ai-training files merged into it.
 *
 * The order of `sources` is the merge order and must stay fixed so generation
 * is byte-reproducible.
 */
export interface ReferenceGroup {
  /** Destination file name without the `.md` extension (for example `overview`). */
  destination: string;

  /** Source ai-training file names, in merge order. */
  sources: string[];
}

/**
 * The fixed mapping from ai-training sources to the five reference files.
 *
 * `README.md` is intentionally omitted: it is index noise, not reference
 * material. Groups with more than one source are concatenated in order.
 */
export const REFERENCE_GROUPS: readonly ReferenceGroup[] = [
  { destination: 'overview', sources: ['00-overview.md'] },
  { destination: 'usage', sources: ['01-core-concepts.md', '02-basic-usage.md'] },
  {
    destination: 'recipes',
    sources: ['03-advanced-patterns.md', '05-common-scenarios.md', '09-examples-library.md'],
  },
  {
    destination: 'pitfalls',
    sources: ['04-best-practices.md', '06-testing-patterns.md', '07-troubleshooting.md'],
  },
  { destination: 'api', sources: ['08-api-reference.md'] },
];

/**
 * Map from an ai-training source file to the reference it is merged into.
 *
 * Because every reference for a package lives in the same directory, a link to
 * one source file can be rewritten to the merged file's name without any
 * directory arithmetic.
 */
const AI_TRAINING_SOURCE_TO_REFERENCE: ReadonlyMap<string, string> = new Map(
  REFERENCE_GROUPS.flatMap(group =>
    group.sources.map(source => [source, group.destination] as const)
  )
);

/**
 * Replaces any remaining private workspace scope with the public package name.
 *
 * `rewriteImports()` deliberately skips `@blendsdk/` inside URLs and file paths
 * so it can share logic with the techdocs transformer. Skill content must never
 * mention the private scope at all, so after the import rewrite this final pass
 * converts leftover occurrences (for example in an error transcript that names
 * `node_modules/@blendsdk/i18n/package.json`) to the public form.
 *
 * @param content - Markdown content
 * @returns Content with no private workspace scope references
 */
export function replacePrivateScope(content: string): string {
  return content.split('@blendsdk/').join('blendsdk/');
}

/**
 * Rewrites links to sibling ai-training files so they point at the merged
 * reference.
 *
 * A source such as `08-api-reference.md` becomes `api.md`, and its sibling
 * `01-core-concepts.md` becomes `usage.md`. Without this, a link like
 * `](./01-core-concepts.md#query-hooks)` would survive the merge and point at a
 * file that no longer exists. Links whose target is not a mapped source are
 * left untouched for the metadata cleaner to drop.
 *
 * @param content - Normalized source markdown
 * @returns Content with sibling links pointing at their merged references
 */
export function rewriteReferenceLinks(content: string): string {
  return content.replace(
    /\]\(\.\/([0-9]{2}-[a-z-]+\.md)(#[^)]*)?\)/g,
    (whole, sourceFile: string, anchor: string | undefined) => {
      const destination = AI_TRAINING_SOURCE_TO_REFERENCE.get(sourceFile);
      return destination ? `](${destination}.md${anchor ?? ''})` : whole;
    }
  );
}

/**
 * One hand-written source file and its destination in the skill tree.
 *
 * Paths are POSIX-style and relative: `source` is relative to the retired MCP
 * documentation root, `destination` is relative to the skill folder.
 */
export interface LegacyFileMapping {
  /** Source path relative to the MCP documentation root. */
  source: string;

  /** Destination path relative to the skill folder. */
  destination: string;
}

/** Documentation root of the retiring MCP package, relative to the monorepo root. */
export const LEGACY_DOCS_ROOT = 'packages/blendsdk-mcp/docs';

/**
 * The five getting-started guides, migrated with renamed, stable file names.
 *
 * The MCP index becomes `guides/index.md`; the numbered files drop their
 * prefixes so links and references stay readable.
 */
export const LEGACY_GUIDES: readonly LegacyFileMapping[] = [
  { source: '01-getting-started/00-index.md', destination: 'references/guides/index.md' },
  {
    source: '01-getting-started/01-installation.md',
    destination: 'references/guides/installation.md',
  },
  {
    source: '01-getting-started/02-project-scaffolding.md',
    destination: 'references/guides/project-scaffolding.md',
  },
  {
    source: '01-getting-started/03-docker-setup.md',
    destination: 'references/guides/docker-setup.md',
  },
  {
    source: '01-getting-started/04-production-deployment.md',
    destination: 'references/guides/production-deployment.md',
  },
];

/**
 * The nine how-to patterns, migrated with their existing numbered names.
 *
 * The MCP pattern index is dropped: `references/index.md` is the routing map.
 */
export const LEGACY_PATTERNS: readonly LegacyFileMapping[] = [
  '01-web-api-crud',
  '02-authentication-jwt',
  '03-caching-patterns',
  '04-database-queries',
  '05-plugin-development',
  '06-code-generation',
  '07-email-sending',
  '08-internationalization',
  '09-testing-patterns',
].map(name => ({
  source: `03-patterns/${name}.md`,
  destination: `references/patterns/${name}.md`,
}));

/**
 * The five project templates, migrated unchanged so `{{PROJECT_NAME}}` stays.
 *
 * The MCP template index is dropped: the templates are self-describing.
 */
export const LEGACY_TEMPLATES: readonly LegacyFileMapping[] = [
  '01-minimal-api',
  '02-full-api',
  '03-api-with-codegen',
  '04-microservice',
  '05-production-docker',
].map(name => ({
  source: `06-templates/${name}.md`,
  destination: `assets/templates/${name}.md`,
}));

/**
 * Hand-written architecture files merged into a single reference.
 *
 * The MCP architecture index, project-structure and design-patterns documents
 * are concatenated; the dependency graph is not copied but regenerated from
 * package metadata by the generator.
 */
export const LEGACY_ARCHITECTURE_SOURCES: readonly string[] = [
  '04-architecture/00-index.md',
  '04-architecture/02-project-structure.md',
  '04-architecture/03-design-patterns.md',
];

/** Destination of the merged architecture reference, relative to the skill folder. */
export const LEGACY_ARCHITECTURE_DESTINATION = 'references/architecture.md';

/**
 * Builds the complete map of migrated source paths to skill destinations.
 *
 * The keys are POSIX paths relative to {@link LEGACY_DOCS_ROOT}; the values are
 * POSIX paths relative to the skill folder. The map drives both file copying and
 * the rewriting of links that point at other migrated files.
 *
 * @returns Map of source path to destination path
 */
export function buildLegacyLinkMap(): Map<string, string> {
  const map = new Map<string, string>();

  for (const { source, destination } of [
    ...LEGACY_GUIDES,
    ...LEGACY_PATTERNS,
    ...LEGACY_TEMPLATES,
  ]) {
    map.set(source, destination);
  }

  for (const source of LEGACY_ARCHITECTURE_SOURCES) {
    map.set(source, LEGACY_ARCHITECTURE_DESTINATION);
  }

  return map;
}

/**
 * A reference group whose source paths have been resolved and validated.
 */
export interface ResolvedReferenceGroup {
  /** Destination file name without the `.md` extension. */
  destination: string;

  /** Absolute paths to the source files, in merge order. */
  sourcePaths: string[];
}

/**
 * Maximum number of symlink hops followed before resolving fails closed.
 *
 * Mirrors the operating system's loop limit; a symlink cycle must produce an
 * error rather than hang the generator.
 */
const MAX_SYMLINK_DEPTH = 40;

/**
 * Resolves a path through symlinks, including dangling links and missing paths.
 *
 * `fs.realpathSync` fails on a missing path, and `fs.existsSync` reports a
 * dangling symlink as absent. Either would let a symlink slip past a
 * containment check. This helper walks the path component by component using
 * `lstatSync` (which sees dangling links) and `readlinkSync`, so every symlink
 * is followed to the path the operating system would ultimately touch. Missing
 * trailing components are re-appended lexically.
 *
 * @param target - Absolute path to resolve
 * @param depth - Internal recursion depth used to stop symlink cycles
 * @returns The fully symlink-resolved path
 * @throws SkillGenerationError when the symlink chain exceeds the hop limit
 */
function resolveThroughSymlinks(target: string, depth = 0): string {
  if (depth > MAX_SYMLINK_DEPTH) {
    throw new SkillGenerationError(`Too many symbolic links while resolving ${target}`);
  }

  const absolute = path.resolve(target);
  const filesystemRoot = path.parse(absolute).root;
  const segments = absolute.slice(filesystemRoot.length).split(path.sep).filter(Boolean);

  let resolved = filesystemRoot;
  const missingSegments: string[] = [];

  for (const segment of segments) {
    if (missingSegments.length > 0) {
      missingSegments.push(segment);
      continue;
    }

    const candidate = path.join(resolved, segment);

    let stats: fs.Stats;
    try {
      stats = fs.lstatSync(candidate);
    } catch {
      missingSegments.push(segment);
      continue;
    }

    if (stats.isSymbolicLink()) {
      const linkTarget = fs.readlinkSync(candidate);
      const absoluteTarget = path.isAbsolute(linkTarget)
        ? linkTarget
        : path.resolve(resolved, linkTarget);
      resolved = resolveThroughSymlinks(absoluteTarget, depth + 1);
    } else {
      resolved = candidate;
    }
  }

  return missingSegments.length > 0 ? path.join(resolved, ...missingSegments) : resolved;
}

/**
 * Resolves a candidate path and rejects it when it escapes a root directory.
 *
 * Both the root and the candidate are resolved through symlinks, including for
 * paths that do not exist yet. A symlinked directory anywhere on the candidate's
 * path that points outside the root is therefore rejected before any file is
 * read or written.
 *
 * @param rootDir - Absolute path to the directory the candidate must stay inside
 * @param candidate - Absolute or relative path to validate
 * @returns The resolved candidate path when it is contained by `rootDir`
 * @throws SkillGenerationError when the candidate escapes `rootDir`
 */
export function assertWithinRoot(rootDir: string, candidate: string): string {
  const root = path.resolve(rootDir);
  const target = path.resolve(candidate);

  const rootResolved = resolveThroughSymlinks(root);
  const targetResolved = resolveThroughSymlinks(target);

  const relative = path.relative(rootResolved, targetResolved);

  if (relative === '') {
    return target;
  }

  if (relative.startsWith('..') || path.isAbsolute(relative)) {
    throw new SkillGenerationError(`Refusing path outside ${root}: ${target}`);
  }

  return target;
}

/**
 * Resolves and validates every source file for one package.
 *
 * The function fails closed: a missing `ai-training/` directory, a missing
 * mapped source file, or a source that resolves outside the package directory
 * raises an error before the caller has a chance to write anything.
 *
 * @param packageDir - Absolute path to the package directory
 * @returns The reference groups with absolute, validated source paths
 * @throws SkillGenerationError when a required source is missing or escapes
 */
export function resolveReferenceGroups(packageDir: string): ResolvedReferenceGroup[] {
  const aiTrainingDir = path.join(packageDir, 'ai-training');

  if (!fs.existsSync(aiTrainingDir)) {
    throw new SkillGenerationError(
      `Missing ai-training directory for package: expected ${aiTrainingDir}`
    );
  }

  return REFERENCE_GROUPS.map(group => {
    const sourcePaths = group.sources.map(source => {
      const candidate = path.join(aiTrainingDir, source);

      if (!fs.existsSync(candidate)) {
        throw new SkillGenerationError(`Missing ai-training file: ${candidate}`);
      }

      return assertWithinRoot(packageDir, candidate);
    });

    return { destination: group.destination, sourcePaths };
  });
}
