import { afterEach, describe, expect, test } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { checkClient, generateClient } from '../src/generator/client-generator.js';
import { main as apiMain } from '../src/api/cli.js';
import type {
  OpenAPIDocument,
  OpenAPIResponse,
  OpenAPISchema,
} from '../src/generator/openapi-types.js';

/**
 * Behavioural contract for the client generator and the `blendsdk api` commands.
 *
 * The generator turns a committed OpenAPI 3.1 document into typed TypeScript.
 * These tests pin the observable output: the files written, the generated
 * marker, deterministic and idempotent writes, stale pruning, the group and
 * method naming rules, the strictness split between `generate` and `check`, and
 * the CLI exit codes. They are written against the required behaviour only and
 * do not inspect the generator's internals.
 *
 * @module codegen/tests/client-generator.spec
 */

/** The stable marker every generated file must start with. */
const GENERATED_MARKER = '// Generated by `blendsdk api generate` — do not edit by hand.';

/** Directories created by a test, removed after each test. */
const tempDirectories: string[] = [];

/**
 * Creates an empty temporary directory.
 *
 * @returns The absolute path of the new directory.
 */
function tempDirectory(): string {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'blendsdk-client-generator-'));
  tempDirectories.push(directory);
  return directory;
}

afterEach(() => {
  while (tempDirectories.length > 0) {
    const directory = tempDirectories.pop();
    if (directory) {
      fs.rmSync(directory, { recursive: true, force: true });
    }
  }
});

/**
 * Builds one operation response with an optional JSON schema.
 *
 * @param schema - The success schema, when the operation defines one.
 * @returns A response object keyed by status code.
 */
function success(schema?: OpenAPISchema): Record<string, OpenAPIResponse> {
  return {
    200: {
      description: 'Success',
      ...(schema ? { content: { 'application/json': { schema } } } : {}),
    },
  };
}

/**
 * Builds a minimal OpenAPI 3.1 document from a path map.
 *
 * @param paths - The document paths.
 * @param schemas - Optional reusable component schemas.
 * @returns A complete OpenAPI document.
 */
function document(
  paths: OpenAPIDocument['paths'],
  schemas?: Record<string, OpenAPISchema>
): OpenAPIDocument {
  return {
    openapi: '3.1.0',
    info: { title: 'Test API', version: '1.0.0' },
    paths,
    ...(schemas ? { components: { schemas } } : {}),
  };
}

/** A document with two product operations and one order operation. */
function sampleDocument(): OpenAPIDocument {
  return document(
    {
      '/api/products': {
        get: {
          operationId: 'listProducts',
          tags: ['products'],
          responses: success({ type: 'array', items: { type: 'object' } }),
        },
        post: {
          operationId: 'createProduct',
          tags: ['products'],
          requestBody: {
            required: true,
            content: { 'application/json': { schema: { type: 'object' } } },
          },
          responses: success({ type: 'object' }),
        },
      },
      '/api/products/{id}': {
        get: {
          operationId: 'getProduct',
          tags: ['products'],
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          responses: success({ $ref: '#/components/schemas/Product' }),
        },
      },
      '/api/orders': {
        get: {
          operationId: 'listOrders',
          tags: ['orders'],
          responses: success({ type: 'array', items: { type: 'object' } }),
        },
      },
    },
    { Product: { type: 'object', properties: { id: { type: 'number' } } } }
  );
}

/**
 * Reads a generated file as UTF-8 text.
 *
 * @param directory - The output directory.
 * @param name - The file name.
 * @returns The file contents.
 */
function read(directory: string, name: string): string {
  return fs.readFileSync(path.join(directory, name), 'utf8');
}

/**
 * Runs `blendsdk api` and captures its output.
 *
 * @param argv - The arguments after the executable name.
 * @returns The exit code and the captured standard error.
 */
async function runApi(argv: string[]): Promise<{ code: number; stderr: string }> {
  let stderr = '';
  const code = await apiMain(argv, {
    stdout: () => undefined,
    stderr: message => {
      stderr += `${message}\n`;
    },
  });
  return { code, stderr };
}

describe('client generator output contract', () => {
  test('writes the expected files, each starting with the generated marker', async () => {
    const directory = tempDirectory();

    const result = await generateClient(sampleDocument(), { outputDir: directory });

    expect(result.files).toHaveLength(3);
    for (const name of ['types.ts', 'client.ts', 'index.ts']) {
      expect(fs.existsSync(path.join(directory, name))).toBe(true);
      expect(read(directory, name).startsWith(GENERATED_MARKER)).toBe(true);
    }
  });

  test('re-exports the named component schema types from types.ts', async () => {
    const directory = tempDirectory();

    await generateClient(sampleDocument(), { outputDir: directory });

    expect(read(directory, 'types.ts')).toContain('Product');
  });

  test('is byte-identical when run twice with no contract change', async () => {
    const directory = tempDirectory();
    const options = { outputDir: directory };

    await generateClient(sampleDocument(), options);
    const first = {
      types: read(directory, 'types.ts'),
      client: read(directory, 'client.ts'),
      index: read(directory, 'index.ts'),
    };

    await generateClient(sampleDocument(), options);

    expect(read(directory, 'types.ts')).toBe(first.types);
    expect(read(directory, 'client.ts')).toBe(first.client);
    expect(read(directory, 'index.ts')).toBe(first.index);
  });

  test('prunes a method that no longer exists in the contract', async () => {
    const directory = tempDirectory();
    const options = { outputDir: directory };
    const full = sampleDocument();

    await generateClient(full, options);
    expect(read(directory, 'client.ts')).toContain('getProduct');

    const reduced: OpenAPIDocument = {
      ...full,
      paths: { ...full.paths },
    };
    delete reduced.paths['/api/products/{id}'];
    await generateClient(reduced, options);

    expect(read(directory, 'client.ts')).not.toContain('getProduct');
  });

  test('prunes a stale generated file when a group disappears', async () => {
    const directory = tempDirectory();
    const options = { outputDir: directory, splitByGroup: true };
    const full = sampleDocument();

    await generateClient(full, options);
    expect(fs.existsSync(path.join(directory, 'client.orders.ts'))).toBe(true);

    await generateClient(document({ '/api/products': full.paths['/api/products'] }), options);

    expect(fs.existsSync(path.join(directory, 'client.orders.ts'))).toBe(false);
    expect(fs.existsSync(path.join(directory, 'client.ts'))).toBe(true);
  });

  test('emits one file per group plus a barrel when splitByGroup is set', async () => {
    const directory = tempDirectory();

    await generateClient(sampleDocument(), { outputDir: directory, splitByGroup: true });

    expect(fs.existsSync(path.join(directory, 'client.products.ts'))).toBe(true);
    expect(fs.existsSync(path.join(directory, 'client.orders.ts'))).toBe(true);
    expect(fs.existsSync(path.join(directory, 'client.ts'))).toBe(true);
  });

  test('sanitizes a hyphenated tag into a valid identifier group', async () => {
    const directory = tempDirectory();
    const doc = document({
      '/api/catalog': {
        get: {
          operationId: 'listCatalog',
          tags: ['product-catalog'],
          responses: success({ type: 'object' }),
        },
      },
    });

    await generateClient(doc, { outputDir: directory });

    expect(read(directory, 'client.ts')).toContain('productCatalog');
  });

  test('escapes a reserved operationId with a trailing underscore and warns', async () => {
    const directory = tempDirectory();
    const doc = document({
      '/api/products/{id}': {
        delete: {
          operationId: 'delete',
          tags: ['products'],
          responses: success({ type: 'object' }),
        },
      },
    });

    const result = await generateClient(doc, { outputDir: directory });

    expect(read(directory, 'client.ts')).toMatch(/\bdelete_\b/);
    expect(result.issues.some(issue => issue.severity === 'warning')).toBe(true);
  });

  test('uses the configured runtime import specifier in the generated client', async () => {
    const directory = tempDirectory();

    await generateClient(sampleDocument(), {
      outputDir: directory,
      runtimeImport: '@blendsdk/api-client',
    });

    expect(read(directory, 'client.ts')).toContain('@blendsdk/api-client');
  });

  test('fails generation when two operations share an operationId', async () => {
    const directory = tempDirectory();
    const doc = document({
      '/api/a': {
        get: { operationId: 'duplicate', tags: ['a'], responses: success({ type: 'object' }) },
      },
      '/api/b': {
        post: { operationId: 'duplicate', tags: ['b'], responses: success({ type: 'object' }) },
      },
    });

    const error = await generateClient(doc, { outputDir: directory }).catch(
      (caught: unknown) => caught
    );

    expect(error).toBeInstanceOf(Error);
    const message = (error as Error).message;
    expect(message).toContain('/api/a');
    expect(message).toContain('/api/b');
  });

  test('uses a deterministic fallback method name and warns when operationId is missing', async () => {
    const directory = tempDirectory();
    const doc = document({
      '/api/products/{id}': {
        get: {
          tags: ['products'],
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          responses: success({ type: 'object' }),
        },
      },
    });

    const result = await generateClient(doc, { outputDir: directory });

    expect(read(directory, 'client.ts')).toContain('productsGetById');
    expect(result.issues.some(issue => issue.severity === 'warning')).toBe(true);
  });

  test('treats a missing 2xx response schema as an unknown result and warns', async () => {
    const directory = tempDirectory();
    const doc = document({
      '/api/things': {
        get: { operationId: 'listThings', tags: ['things'], responses: success() },
      },
    });

    const result = await generateClient(doc, { outputDir: directory });

    expect(read(directory, 'client.ts')).toContain('Promise<unknown>');
    expect(result.issues.some(issue => issue.severity === 'warning')).toBe(true);
  });

  test('defines an inline success schema as a structural result alias', async () => {
    const directory = tempDirectory();
    const doc = document({
      '/api/things': {
        post: {
          operationId: 'createThing',
          tags: ['things'],
          responses: success({
            type: 'object',
            properties: { id: { type: 'number' } },
            required: ['id'],
          }),
        },
      },
    });

    await generateClient(doc, { outputDir: directory });

    const types = read(directory, 'types.ts');
    expect(types).toContain('export type ThingsCreateThingResult = {');
    expect(types).not.toContain('ThingsCreateThingResult = ThingsCreateThingResult');
    expect(read(directory, 'client.ts')).toContain('Promise<ThingsCreateThingResult>');
  });

  test('wraps a body-envelope result in PaginatedResponse and imports it', async () => {
    const directory = tempDirectory();
    const doc = document({
      '/api/orders': {
        get: {
          operationId: 'listOrders',
          tags: ['orders'],
          'x-blend-envelope': 'body',
          responses: success({ type: 'array', items: { type: 'object' } }),
        },
      },
    });

    await generateClient(doc, { outputDir: directory });

    const types = read(directory, 'types.ts');
    expect(types).toContain('PaginatedResponse<');
    expect(types).toContain('OrdersListOrdersResult');
    expect(read(directory, 'client.ts')).toContain('Promise<OrdersListOrdersResult>');
  });

  test('escapes an operation name that tries to inject code', async () => {
    const directory = tempDirectory();
    const doc = document({
      "/api/evil'}": {
        get: {
          operationId: "evil'); process.exit(1); //",
          tags: ['evil'],
          responses: success({ type: 'object' }),
        },
      },
    });

    await generateClient(doc, { outputDir: directory });

    // The dangerous text may appear as data inside an escaped string literal,
    // but it must never become a statement in the generated file.
    expect(read(directory, 'client.ts')).not.toMatch(/^\s*process\.exit/m);
    expect(read(directory, 'types.ts')).not.toMatch(/^\s*process\.exit/m);
    expect(read(directory, 'client.ts')).toContain('export function createAppClient');
  });
});

describe('client generator drift check', () => {
  test('reports no drift immediately after a clean generate', async () => {
    const directory = tempDirectory();
    const doc = sampleDocument();
    await generateClient(doc, { outputDir: directory });

    const result = await checkClient(doc, { outputDir: directory });

    expect(result.drifted).toBe(false);
  });

  test('reports drift when a committed client file is modified', async () => {
    const directory = tempDirectory();
    const doc = sampleDocument();
    await generateClient(doc, { outputDir: directory });
    fs.appendFileSync(path.join(directory, 'client.ts'), '\n// hand edit\n');

    const result = await checkClient(doc, { outputDir: directory });

    expect(result.drifted).toBe(true);
  });

  test('reports an error when an operation has no operationId', async () => {
    const directory = tempDirectory();
    const doc = document({
      '/api/products/{id}': {
        get: {
          tags: ['products'],
          parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string' } }],
          responses: success({ type: 'object' }),
        },
      },
    });

    const result = await checkClient(doc, { outputDir: directory });

    expect(result.issues.some(issue => issue.severity === 'error')).toBe(true);
  });

  test('reports an error when an operation has no 2xx response schema', async () => {
    const directory = tempDirectory();
    const doc = document({
      '/api/things': {
        get: { operationId: 'listThings', tags: ['things'], responses: success() },
      },
    });

    const result = await checkClient(doc, { outputDir: directory });

    expect(result.issues.some(issue => issue.severity === 'error')).toBe(true);
  });
});

describe('blendsdk api command', () => {
  /** Writes a valid contract config and returns its path. */
  function writeValidConfig(directory: string): string {
    const configPath = path.join(directory, 'blendsdk.api.ts');
    fs.writeFileSync(
      configPath,
      [
        'class ProductsController {',
        '  routes() {',
        '    return [',
        '      {',
        "        method: 'get',",
        "        path: '/',",
        '        handler: () => undefined,',
        '        openapi: {',
        "          operationId: 'listProducts',",
        "          tags: ['products'],",
        "          responses: [{ statusCode: 200, description: 'Success', schema: {} }],",
        '        },',
        '      },',
        '    ];',
        '  }',
        '}',
        'export default {',
        "  outputDir: 'client',",
        "  contractFile: 'api.json',",
        "  controllers: [{ basePath: '/api/products', controller: ProductsController }],",
        "  openapi: { title: 'CLI API', version: '1.0.0' },",
        '};',
        '',
      ].join('\n')
    );
    return configPath;
  }

  test('generate writes the contract and the client, then check is clean', async () => {
    const directory = tempDirectory();
    const configPath = writeValidConfig(directory);

    const generated = await runApi(['api', 'generate', '--config', configPath]);

    expect(generated.code).toBe(0);
    expect(fs.existsSync(path.join(directory, 'api.json'))).toBe(true);
    expect(fs.existsSync(path.join(directory, 'client', 'client.ts'))).toBe(true);

    const clean = await runApi(['api', 'check', '--config', configPath]);
    expect(clean.code).toBe(0);
  });

  test('check exits 1 and lists drift when the committed client is stale', async () => {
    const directory = tempDirectory();
    const configPath = writeValidConfig(directory);
    await runApi(['api', 'generate', '--config', configPath]);
    fs.appendFileSync(path.join(directory, 'client', 'client.ts'), '\n// drifted\n');

    const result = await runApi(['api', 'check', '--config', configPath]);

    expect(result.code).toBe(1);
    expect(result.stderr.toLowerCase()).toContain('client.ts');
  });

  test('check exits 1 when only the committed api.json drifted', async () => {
    const directory = tempDirectory();
    const configPath = writeValidConfig(directory);
    await runApi(['api', 'generate', '--config', configPath]);
    const contractPath = path.join(directory, 'api.json');
    const contract = JSON.parse(fs.readFileSync(contractPath, 'utf8')) as {
      info: { title: string };
    };
    contract.info.title = 'Changed title';
    fs.writeFileSync(contractPath, JSON.stringify(contract, null, 2));

    const result = await runApi(['api', 'check', '--config', configPath]);

    expect(result.code).toBe(1);
    expect(result.stderr.toLowerCase()).toContain('api.json');
  });

  test('generate exits 2 and writes nothing when the config is missing', async () => {
    const directory = tempDirectory();
    const missing = path.join(directory, 'does-not-exist.ts');

    const result = await runApi(['api', 'generate', '--config', missing]);

    expect(result.code).toBe(2);
    expect(fs.existsSync(path.join(directory, 'api.json'))).toBe(false);
    expect(fs.existsSync(path.join(directory, 'client'))).toBe(false);
  });

  test('generate exits 2 and writes nothing when the config is invalid', async () => {
    const directory = tempDirectory();
    const configPath = path.join(directory, 'blendsdk.api.ts');
    fs.writeFileSync(configPath, 'export default 42;\n');

    const result = await runApi(['api', 'generate', '--config', configPath]);

    expect(result.code).toBe(2);
    expect(fs.existsSync(path.join(directory, 'client'))).toBe(false);
  });

  test('check exits 2 when the config is missing', async () => {
    const directory = tempDirectory();
    const missing = path.join(directory, 'does-not-exist.ts');

    const result = await runApi(['api', 'check', '--config', missing]);

    expect(result.code).toBe(2);
  });
});
