/**
 * Specification tests for the skill drift gate.
 *
 * The drift gate regenerates the skill tree into a temporary directory and
 * compares it with the committed tree. A clean tree passes; any hand edit to a
 * generated file makes it fail and reports the changed path. Regenerating the
 * tree restores the clean state.
 *
 * @module skill/tests/check-drift.spec
 */

import fs from 'node:fs';
import path from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { checkDrift } from '../check-drift.js';
import { generateSkillTree } from '../generate.js';
import { FIXTURE_PACKAGE_NAME, createFixtureWorkspace } from './helpers/fixture-workspace.js';

import type { FixtureWorkspace } from './helpers/fixture-workspace.js';

/** The exact generated-file marker required by the content model. */
const EXPECTED_MARKER = '<!-- Generated by scripts/skill/generate.ts — do not edit by hand. -->';

describe('Skill drift gate', () => {
  let workspace: FixtureWorkspace;

  beforeEach(() => {
    workspace = createFixtureWorkspace();
    generateSkillTree({ rootDir: workspace.rootDir });
  });

  afterEach(() => {
    workspace.cleanup();
  });

  it('should report no drift immediately after generation', () => {
    const report = checkDrift({ rootDir: workspace.rootDir });

    expect(report.ok).toBe(true);
    expect(report.changed).toEqual([]);
    expect(report.missing).toEqual([]);
    expect(report.added).toEqual([]);
  });

  it('should fail and name the path when a generated reference is hand-edited', () => {
    const referencePath = `references/packages/${FIXTURE_PACKAGE_NAME}/overview.md`;
    const absolutePath = path.join(workspace.skillDir, referencePath);
    const original = fs.readFileSync(absolutePath, 'utf-8');
    fs.writeFileSync(
      absolutePath,
      original.replace(EXPECTED_MARKER, `A hand edit that must not survive.\n${EXPECTED_MARKER}`),
      'utf-8'
    );

    const report = checkDrift({ rootDir: workspace.rootDir });

    expect(report.ok).toBe(false);
    expect(report.changed).toContain(referencePath);
  }, 15_000);

  it('should return to a clean state after the tree is regenerated', () => {
    const referencePath = `references/packages/${FIXTURE_PACKAGE_NAME}/overview.md`;
    const absolutePath = path.join(workspace.skillDir, referencePath);
    const original = fs.readFileSync(absolutePath, 'utf-8');
    fs.writeFileSync(
      absolutePath,
      original.replace(EXPECTED_MARKER, `A hand edit that must not survive.\n${EXPECTED_MARKER}`),
      'utf-8'
    );

    generateSkillTree({ rootDir: workspace.rootDir });

    const report = checkDrift({ rootDir: workspace.rootDir });
    expect(report.ok).toBe(true);
  }, 15_000);

  it('should return to a clean state after a package is removed and regenerated', () => {
    fs.rmSync(path.join(workspace.rootDir, 'packages', FIXTURE_PACKAGE_NAME), {
      recursive: true,
      force: true,
    });

    generateSkillTree({ rootDir: workspace.rootDir });

    const report = checkDrift({ rootDir: workspace.rootDir });
    expect(report.ok).toBe(true);
    expect(report.missing).toEqual([]);
    expect(
      fs.existsSync(
        path.join(workspace.skillDir, 'references', 'packages', FIXTURE_PACKAGE_NAME)
      )
    ).toBe(false);
  }, 15_000);
});
