/**
 * Specification tests for the committed BlendSDK skill content.
 *
 * Unlike the generator tests, these tests read the real `.agents/skills/blendsdk`
 * tree rather than a fixture. They encode the content requirements: full package
 * coverage, a task routing map whose links resolve, public import paths, no SDK
 * version stamp, and the generated-file marker boundary.
 *
 * @module skill/tests/content.spec
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

/** Absolute path to the monorepo root, derived from this test file's location. */
const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..', '..');

/** Absolute path to the committed skill folder. */
const SKILL_DIR = path.join(REPO_ROOT, '.agents', 'skills', 'blendsdk');

/** Absolute path to the committed references folder. */
const REFERENCES_DIR = path.join(SKILL_DIR, 'references');

/**
 * The exact marker required as the last line of every generated file.
 *
 * Asserting against the literal keeps the oracle independent of the generator's
 * constant, so changing the constant cannot silently keep the test green.
 */
const EXPECTED_MARKER = '<!-- Generated by scripts/skill/generate.ts — do not edit by hand. -->';

/** The 19 publishable packages that must each have a reference directory. */
const EXPECTED_PACKAGES = [
  'api-client',
  'authz',
  'blendscript',
  'cmdline',
  'codegen',
  'dbcore',
  'expression',
  'i18n',
  'postgresql',
  'react',
  'stdlib',
  'webafx',
  'webafx-auth',
  'webafx-authz',
  'webafx-cache',
  'webafx-i18n',
  'webafx-mailer',
  'webafx-mailer-azure',
  'webafx-pino',
] as const;

/** The five focused reference files every package directory must contain. */
const EXPECTED_REFERENCE_FILES = ['overview.md', 'usage.md', 'api.md', 'recipes.md', 'pitfalls.md'];

/**
 * External version literals that are legitimate and must not be mistaken for
 * the SDK version: external dependency ranges (for example `express ^5.0.0`,
 * `typescript 5.x`) and protocol examples.
 */
const EXTERNAL_VERSION_ALLOWLIST = new Set(['5.0.0', '5.2.1', '5.6.0', '5.7.0', '5.7.8', '5.9.0']);

/**
 * Task families that `references/index.md` must route to real references.
 *
 * The label is the text the routing table row must contain; the matcher keeps
 * the assertion tolerant of wording while still being specific.
 */
const TASK_FAMILIES: ReadonlyArray<{ label: string; matcher: RegExp }> = [
  { label: 'CRUD', matcher: /\bcrud\b/i },
  { label: 'authentication', matcher: /authenticat|\bauth\b|\bjwt\b/i },
  { label: 'caching', matcher: /cach/i },
  { label: 'database', matcher: /database|postgresql/i },
  { label: 'email', matcher: /email|mailer/i },
  { label: 'i18n', matcher: /\bi18n\b|internationali/i },
  { label: 'logging', matcher: /\blogging\b|\bpass\b|\bpino\b|\blogger\b/i },
  { label: 'codegen', matcher: /codegen|code generation/i },
  { label: 'testing', matcher: /\btesting\b|\btests?\b/i },
];

/**
 * Recursively reads every file under a directory into a map keyed by its path
 * relative to that directory, using forward slashes.
 *
 * @param dir - Absolute path to the directory to read
 * @returns Map of relative path to file content
 */
function readAllFiles(dir: string): Map<string, string> {
  const files = new Map<string, string>();

  if (!fs.existsSync(dir)) {
    return files;
  }

  const walk = (current: string): void => {
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const fullPath = path.join(current, entry.name);

      if (entry.isDirectory()) {
        walk(fullPath);
      } else if (entry.isFile()) {
        const relative = path.relative(dir, fullPath).split(path.sep).join('/');
        files.set(relative, fs.readFileSync(fullPath, 'utf-8'));
      }
    }
  };

  walk(dir);
  return files;
}

/**
 * Reads the current SDK version from the umbrella package.
 *
 * @returns The `version` field of `packages/blendsdk/package.json`
 */
function readSdkVersion(): string {
  const packageJsonPath = path.join(REPO_ROOT, 'packages', 'blendsdk', 'package.json');
  const parsed: unknown = JSON.parse(fs.readFileSync(packageJsonPath, 'utf-8'));

  if (
    typeof parsed !== 'object' ||
    parsed === null ||
    !('version' in parsed) ||
    typeof parsed.version !== 'string'
  ) {
    throw new Error('packages/blendsdk/package.json has no string version field');
  }

  return parsed.version;
}

/** The SDK's major version, used to scope the version-literal guard. */
const SDK_MAJOR = readSdkVersion().split('.')[0];

/**
 * Returns every SDK-major version token in the content that is not on the
 * external allowlist. Any result means an SDK version leaked into the content.
 *
 * @param content - Markdown content to scan
 * @returns Unlisted version tokens, in order of appearance
 */
function unlistedVersionTokens(content: string): string[] {
  const pattern = new RegExp(`\\b${SDK_MAJOR}\\.\\d+\\.\\d+\\b`, 'g');
  const tokens: string[] = [];

  for (const match of content.matchAll(pattern)) {
    if (!EXTERNAL_VERSION_ALLOWLIST.has(match[0])) {
      tokens.push(match[0]);
    }
  }

  return tokens;
}

/**
 * Reads every ai-training markdown file across the publishable packages.
 *
 * @returns Map of a display path to file content
 */
function readAiTrainingFiles(): Map<string, string> {
  const files = new Map<string, string>();
  const packagesDir = path.join(REPO_ROOT, 'packages');

  for (const entry of fs.readdirSync(packagesDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) {
      continue;
    }

    const aiTrainingDir = path.join(packagesDir, entry.name, 'ai-training');
    if (!fs.existsSync(aiTrainingDir)) {
      continue;
    }

    for (const [relative, content] of readAllFiles(aiTrainingDir)) {
      files.set(`${entry.name}/ai-training/${relative}`, content);
    }
  }

  return files;
}

describe('Committed skill content', () => {
  it('exposes exactly the 16 package reference directories, each with five references', () => {
    const packagesDir = path.join(REFERENCES_DIR, 'packages');

    expect(fs.existsSync(packagesDir), `missing ${packagesDir}`).toBe(true);

    const directories = fs
      .readdirSync(packagesDir, { withFileTypes: true })
      .filter(entry => entry.isDirectory())
      .map(entry => entry.name)
      .sort();

    expect(directories).toEqual([...EXPECTED_PACKAGES].sort());

    for (const packageName of EXPECTED_PACKAGES) {
      const files = fs.readdirSync(path.join(packagesDir, packageName)).sort();
      expect(files, `unexpected references in ${packageName}`).toEqual(
        [...EXPECTED_REFERENCE_FILES].sort()
      );
    }
  });

  it('routes every documented task family to a reference path that exists', () => {
    const indexPath = path.join(REFERENCES_DIR, 'index.md');
    expect(fs.existsSync(indexPath), 'missing references/index.md').toBe(true);

    const content = fs.readFileSync(indexPath, 'utf-8');
    const targets = [...content.matchAll(/\]\(([^)]+)\)/g)].map(match => match[1].split('#')[0]);

    expect(targets.length, 'references/index.md contains no links').toBeGreaterThan(0);

    for (const target of targets) {
      const resolved = path.resolve(REFERENCES_DIR, target);
      expect(fs.existsSync(resolved), `dangling link in index.md: ${target}`).toBe(true);
    }

    const lines = content.split('\n');

    for (const family of TASK_FAMILIES) {
      const row = lines.find(line => family.matcher.test(line) && /\]\([^)]+\)/.test(line));
      expect(row, `references/index.md does not route the "${family.label}" family`).toBeDefined();
    }
  });

  it('never references the private @blendsdk/ workspace scope', () => {
    for (const [relativePath, content] of readAllFiles(SKILL_DIR)) {
      expect(content.includes('@blendsdk/'), `${relativePath} contains @blendsdk/`).toBe(false);
    }
  });

  it('never contains an SDK version header or an unlisted SDK version token', () => {
    const files = new Map([...readAllFiles(SKILL_DIR), ...readAiTrainingFiles()]);

    for (const [relativePath, content] of files) {
      expect(content.includes('> **Version**:'), `${relativePath} has a version header`).toBe(
        false
      );
      expect(
        unlistedVersionTokens(content),
        `${relativePath} contains an SDK version token`
      ).toEqual([]);
    }
  });

  it('does not treat allowlisted external versions as SDK version tokens', () => {
    expect(unlistedVersionTokens('express ^5.0.0 and typescript 5.7.0')).toEqual([]);
    expect(unlistedVersionTokens('installed blendsdk 5.54.0')).toEqual(['5.54.0']);
  });

  it('marks every generated file and leaves hand-written files unmarked', () => {
    const tree = readAllFiles(SKILL_DIR);

    const generatedFiles = [
      'references/index.md',
      'references/dependency-graph.md',
      ...EXPECTED_PACKAGES.flatMap(packageName =>
        EXPECTED_REFERENCE_FILES.map(file => `references/packages/${packageName}/${file}`)
      ),
    ];

    const handWrittenFiles = [
      'SKILL.md',
      'references/architecture.md',
      ...[
        'index.md',
        'installation.md',
        'project-scaffolding.md',
        'docker-setup.md',
        'production-deployment.md',
      ].map(file => `references/guides/${file}`),
      ...[
        '01-web-api-crud.md',
        '02-authentication-jwt.md',
        '03-caching-patterns.md',
        '04-database-queries.md',
        '05-plugin-development.md',
        '06-code-generation.md',
        '07-email-sending.md',
        '08-internationalization.md',
        '09-testing-patterns.md',
        '10-client-sdk-generation.md',
      ].map(file => `references/patterns/${file}`),
      ...[
        '01-minimal-api.md',
        '02-full-api.md',
        '03-api-with-codegen.md',
        '04-microservice.md',
        '05-production-docker.md',
        '06-api-with-client-sdk.md',
      ].map(file => `assets/templates/${file}`),
    ];

    for (const relativePath of generatedFiles) {
      const content = tree.get(relativePath);
      expect(content, `missing generated file ${relativePath}`).toBeDefined();
      expect(
        content?.trimEnd().endsWith(EXPECTED_MARKER),
        `generated file ${relativePath} does not end with the marker`
      ).toBe(true);
    }

    for (const relativePath of handWrittenFiles) {
      const content = tree.get(relativePath);
      expect(content, `missing hand-written file ${relativePath}`).toBeDefined();
      expect(
        content?.includes(EXPECTED_MARKER),
        `hand-written file ${relativePath} carries the generated marker`
      ).toBe(false);
    }
  });
});
