/**
 * Specification tests for deterministic skill generation.
 *
 * These tests describe the generator's contract from the requirements, not its
 * implementation: output is byte-reproducible, hand-written files are never
 * rewritten, imports use the public `blendsdk/` form, no version header is
 * emitted, generated files carry the marker, and unsafe sources are rejected
 * before anything is written.
 *
 * Every test runs against a throwaway monorepo seeded from `tests/fixtures/`.
 * The real `.agents/skills/blendsdk` tree is never touched.
 *
 * @module skill/tests/generate.spec
 */

import fs from 'node:fs';
import path from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { generateSkillTree } from '../generate.js';
import { FIXTURE_PACKAGE_NAME, createFixtureWorkspace, readTree } from './helpers/fixture-workspace.js';

import type { FixtureWorkspace } from './helpers/fixture-workspace.js';

/**
 * The exact marker required as the last line of every generated file.
 *
 * The spec asserts against this literal rather than the module constant so a
 * change to the constant cannot silently keep the oracle green while violating
 * the requirement.
 */
const EXPECTED_MARKER = '<!-- Generated by scripts/skill/generate.ts — do not edit by hand. -->';

/**
 * Returns only the generated files from a committed tree.
 *
 * Hand-written and migrated files carry no marker, so the marker is the
 * boundary between "the generator owns this file" and "a human owns it".
 *
 * @param tree - Map of relative path to content
 * @returns Map containing only files that end with the generated marker
 */
function generatedFiles(tree: Map<string, string>): Map<string, string> {
  const generated = new Map<string, string>();

  for (const [relativePath, content] of tree) {
    if (content.trimEnd().endsWith(EXPECTED_MARKER)) {
      generated.set(relativePath, content);
    }
  }

  return generated;
}

describe('Skill generator', () => {
  let workspace: FixtureWorkspace;

  beforeEach(() => {
    workspace = createFixtureWorkspace();
  });

  afterEach(() => {
    workspace.cleanup();
  });

  it('should produce byte-identical output when run twice over the same sources', () => {
    generateSkillTree({ rootDir: workspace.rootDir });
    const firstRun = readTree(workspace.skillDir);

    generateSkillTree({ rootDir: workspace.rootDir });
    const secondRun = readTree(workspace.skillDir);

    expect([...secondRun.keys()].sort()).toEqual([...firstRun.keys()].sort());

    for (const [relativePath, content] of firstRun) {
      expect(secondRun.get(relativePath), `byte mismatch in ${relativePath}`).toBe(content);
    }
  });

  it('should leave the hand-written SKILL.md byte-identical', () => {
    const skillPath = path.join(workspace.skillDir, 'SKILL.md');
    const before = fs.readFileSync(skillPath);

    generateSkillTree({ rootDir: workspace.rootDir });

    expect(fs.readFileSync(skillPath).equals(before)).toBe(true);
  });

  it('should rewrite monorepo imports to public blendsdk subpaths', () => {
    generateSkillTree({ rootDir: workspace.rootDir });
    const generated = generatedFiles(readTree(workspace.skillDir));
    const combined = [...generated.values()].join('\n');

    expect(combined).toContain('blendsdk/webafx');
    expect(combined).toContain('blendsdk/i18n-node');
    expect(combined).not.toContain('@blendsdk/');
  });

  it('should emit no version header in generated references', () => {
    generateSkillTree({ rootDir: workspace.rootDir });
    const generated = generatedFiles(readTree(workspace.skillDir));
    const combined = [...generated.values()].join('\n');

    expect(combined).not.toContain('**Version**');
    expect(combined).toContain(`> **Package**: \`blendsdk/${FIXTURE_PACKAGE_NAME}\``);
  });

  it('should mark generated files but never mark the hand-written SKILL.md', () => {
    generateSkillTree({ rootDir: workspace.rootDir });
    const tree = readTree(workspace.skillDir);

    const overviewPath = `references/packages/${FIXTURE_PACKAGE_NAME}/overview.md`;
    expect(tree.has(overviewPath)).toBe(true);
    expect(tree.get(overviewPath)?.trimEnd().endsWith(EXPECTED_MARKER)).toBe(true);

    const skillFile = tree.get('SKILL.md');
    expect(skillFile).toBeDefined();
    expect(skillFile?.includes(EXPECTED_MARKER)).toBe(false);
  });

  it('should reject a source path that escapes the package directory before writing', () => {
    const escapingSource = path.join(workspace.packageDir, 'ai-training', '01-core-concepts.md');
    fs.rmSync(escapingSource);
    fs.symlinkSync(path.join(workspace.skillDir, 'SKILL.md'), escapingSource);

    expect(() => generateSkillTree({ rootDir: workspace.rootDir })).toThrow();

    expect(fs.existsSync(path.join(workspace.skillDir, 'references'))).toBe(false);
  });

  it('should fail naming the file when a source embeds secret material and write nothing', () => {
    const poisonedSource = path.join(workspace.packageDir, 'ai-training', '03-advanced-patterns.md');
    // Build the fake key at runtime so the repository never contains a
    // credential-shaped literal that a secret scanner could flag.
    const fakeKey = `sk-${'x'.repeat(24)}`;
    fs.appendFileSync(poisonedSource, `\nconst leaked = '${fakeKey}';\n`);

    let message = '';
    try {
      generateSkillTree({ rootDir: workspace.rootDir });
    } catch (error) {
      message = error instanceof Error ? error.message : String(error);
    }

    expect(message).toContain('03-advanced-patterns.md');
    expect(fs.existsSync(path.join(workspace.skillDir, 'references'))).toBe(false);
  });

  it('should detect provider-prefixed keys that contain hyphens', () => {
    const poisonedSource = path.join(workspace.packageDir, 'ai-training', '03-advanced-patterns.md');
    const fakeKey = `sk-${['proj', 'a'.repeat(20)].join('-')}`;
    fs.appendFileSync(poisonedSource, `\nconst leaked = '${fakeKey}';\n`);

    let message = '';
    try {
      generateSkillTree({ rootDir: workspace.rootDir });
    } catch (error) {
      message = error instanceof Error ? error.message : String(error);
    }

    expect(message).toContain('03-advanced-patterns.md');
    expect(fs.existsSync(path.join(workspace.skillDir, 'references'))).toBe(false);
  });
});
