/**
 * The API client generator.
 *
 * Reads an OpenAPI 3.1 document and writes a typed client whose methods match
 * the server's operations. The output is plain TypeScript that imports the
 * `@blendsdk/api-client` runtime. Generation is deterministic and idempotent:
 * components and operations are sorted, files are normalized with Prettier, and
 * stale generated files (those carrying the marker) are pruned.
 *
 * Two entry points share one core. {@link generateClient} writes the files;
 * {@link checkClient} regenerates in memory and compares against the committed
 * files, which is the CI drift gate.
 *
 * @module
 */
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import type { Dirent } from 'node:fs';
import { extname, join, resolve } from 'node:path';
import { format, type Options } from 'prettier';
import {
  deriveGroupName,
  fallbackMethodName,
  pascalCase,
  sanitizeIdentifier,
  sanitizeMethodName,
} from './client-naming.js';
import { componentTypeName, defaultResolveReference, schemaToType } from './client-schema.js';
import {
  ClientGenerationError,
  type ClientGeneratorOptions,
  type ContractIssue,
  type GeneratedOperation,
  type GenerationResult,
} from './client-types.js';
import type { OpenAPIDocument, OpenAPIOperation, OpenAPISchema } from './openapi-types.js';

/** The first line of every generated file. */
const GENERATED_MARKER = '// Generated by `blendsdk api generate` — do not edit by hand.';

/** Default runtime import specifier used by generated clients. */
const DEFAULT_RUNTIME_IMPORT = 'blendsdk/api-client';

/** HTTP methods emitted by the generator, in a stable order. */
const HTTP_METHODS = ['get', 'post', 'put', 'patch', 'delete'] as const;

/** Prettier options that match the repository style, for stable output. */
const PRETTIER_OPTIONS: Options = {
  parser: 'typescript',
  singleQuote: true,
  trailingComma: 'es5',
  printWidth: 100,
  tabWidth: 2,
  semi: true,
  arrowParens: 'avoid',
  endOfLine: 'lf',
};

/** A contract problem before its severity is decided by generate/check. */
interface PendingIssue {
  /** True when `check` must treat this as an error. */
  escalates: boolean;
  /** Concise description with the operation location. */
  message: string;
  /** The raw operationId, when present. */
  operationId?: string;
  /** The HTTP method. */
  method: string;
  /** The operation path. */
  path: string;
}

/** One property of an operation's flat params object. */
interface ParamProperty {
  /** The property name as it appears in the document. */
  name: string;
  /** The property's TypeScript type. */
  type: string;
  /** Whether the property is required. */
  required: boolean;
}

/** A fully resolved operation, ready to emit. */
interface OperationModel extends GeneratedOperation {
  /** The flat params properties, empty when the operation takes no values. */
  parameters: ParamProperty[];
  /** The TypeScript result type expression used in the method signature. */
  resultType: string;
  /** The named result alias to emit, when the result is not a component. */
  resultTypeName?: string;
  /** The structural type the result alias is defined as. */
  resultTypeDefinition?: string;
  /** The named params alias to emit, when the operation has params. */
  paramsTypeName?: string;
}

/**
 * Generates a typed client from an OpenAPI 3.1 document.
 *
 * @param document - The OpenAPI document to consume.
 * @param options - Output location and generation flags.
 * @returns The file names written and any contract issues.
 * @throws {ClientGenerationError} When two operations share an `operationId`,
 *   or when `strict` is set and the contract has a warning-level problem.
 *
 * @example
 * ```typescript
 * const result = await generateClient(document, { outputDir: 'src/api-client' });
 * console.log(result.files); // ['client.ts', 'index.ts', 'types.ts']
 * ```
 */
export async function generateClient(
  document: OpenAPIDocument,
  options: ClientGeneratorOptions
): Promise<GenerationResult> {
  const runtimeImport = options.runtimeImport ?? DEFAULT_RUNTIME_IMPORT;
  const { operations, issues } = collectOperations(document);
  const finalized = finalizeIssues(issues, options.strict === true);
  if (finalized.some(issue => issue.severity === 'error')) {
    throw new ClientGenerationError(
      `The contract has errors:\n${finalized.map(issue => `- ${issue.message}`).join('\n')}`
    );
  }

  const emitted = emitFiles(document, operations, runtimeImport, options);
  const files = await formatFiles(emitted);
  const outputDirectory = resolve(options.outputDir);
  await mkdir(outputDirectory, { recursive: true });
  await pruneStaleFiles(outputDirectory, new Set(files.keys()));
  for (const [name, content] of files) {
    await writeFile(join(outputDirectory, name), content, 'utf8');
  }

  return { files: [...files.keys()].sort(), issues: finalized };
}

/**
 * Regenerates a client in memory and compares it against the committed files.
 *
 * @param document - The committed OpenAPI document.
 * @param options - Output location and generation flags.
 * @returns Drift status, the compared file names, and contract issues.
 * @throws {ClientGenerationError} When two operations share an `operationId`.
 */
export async function checkClient(
  document: OpenAPIDocument,
  options: ClientGeneratorOptions
): Promise<GenerationResult> {
  const runtimeImport = options.runtimeImport ?? DEFAULT_RUNTIME_IMPORT;
  const { operations, issues } = collectOperations(document);
  const expected = await formatFiles(emitFiles(document, operations, runtimeImport, options));
  const outputDirectory = resolve(options.outputDir);

  let drifted = false;
  const driftedFiles: string[] = [];
  for (const [name, content] of expected) {
    if ((await readIfExists(join(outputDirectory, name))) !== content) {
      drifted = true;
      driftedFiles.push(name);
    }
  }
  for (const name of await listMarkerFiles(outputDirectory)) {
    if (!expected.has(name)) {
      drifted = true;
      driftedFiles.push(name);
    }
  }

  const finalized = finalizeIssues(issues, true);
  if (finalized.some(issue => issue.severity === 'error')) {
    drifted = true;
  }
  return {
    files: [...expected.keys()].sort(),
    issues: finalized,
    drifted,
    driftedFiles: [...new Set(driftedFiles)].sort(),
  };
}

/**
 * Normalizes an OpenAPI document into the byte-stable JSON text that `generate`
 * writes and `check` compares.
 *
 * @param document - The document to serialize.
 * @returns Prettier-formatted JSON with a trailing newline.
 */
export async function formatOpenApiDocument(document: OpenAPIDocument): Promise<string> {
  return format(JSON.stringify(document, null, 2), { ...PRETTIER_OPTIONS, parser: 'json' });
}

/**
 * Resolves every operation in the document into an emittable model.
 *
 * Paths and methods are visited in a stable order. A missing `operationId` or
 * 2xx schema becomes a pending issue; a duplicate `operationId` (or a duplicate
 * resolved group/method pair) throws.
 *
 * @param document - The OpenAPI document.
 * @returns The operations and the pending issues.
 * @throws {ClientGenerationError} On a duplicate operation or method name.
 */
function collectOperations(document: OpenAPIDocument): {
  operations: OperationModel[];
  issues: PendingIssue[];
} {
  const issues: PendingIssue[] = [];
  const operations: OperationModel[] = [];
  const byOperationId = new Map<string, { method: string; path: string }>();
  const byMethodKey = new Map<string, { method: string; path: string }>();

  const sortedPaths = Object.entries(document.paths).sort(([left], [right]) =>
    left.localeCompare(right)
  );
  for (const [path, pathItem] of sortedPaths) {
    for (const method of HTTP_METHODS) {
      const operation = (pathItem as Record<string, OpenAPIOperation | undefined>)[method];
      if (!operation) {
        continue;
      }
      collectOperation(
        document,
        path,
        method,
        operation,
        operations,
        issues,
        byOperationId,
        byMethodKey
      );
    }
  }
  return { operations, issues };
}

/**
 * Resolves one operation and appends it to the model list.
 *
 * @param document - The OpenAPI document.
 * @param path - The operation path.
 * @param method - The lowercase HTTP method.
 * @param operation - The OpenAPI operation.
 * @param operations - The accumulating model list.
 * @param issues - The accumulating issue list.
 * @param byOperationId - Tracks operationIds for duplicate detection.
 * @param byMethodKey - Tracks resolved group/method pairs for duplicate detection.
 * @throws {ClientGenerationError} On a duplicate operation or method name.
 */
function collectOperation(
  document: OpenAPIDocument,
  path: string,
  method: string,
  operation: OpenAPIOperation,
  operations: OperationModel[],
  issues: PendingIssue[],
  byOperationId: Map<string, { method: string; path: string }>,
  byMethodKey: Map<string, { method: string; path: string }>
): void {
  const group = deriveGroupName(operation.tags, path);
  const rawId = operation.operationId;

  if (rawId) {
    const previous = byOperationId.get(rawId);
    if (previous) {
      throw new ClientGenerationError(
        `Duplicate operationId "${rawId}" used by ${previous.method.toUpperCase()} ${previous.path} and ${method.toUpperCase()} ${path}. OpenAPI operationIds must be unique.`
      );
    }
    byOperationId.set(rawId, { method, path });
  } else {
    issues.push({
      escalates: true,
      message: `Operation ${method.toUpperCase()} ${path} has no operationId; a deterministic method name was generated.`,
      method,
      path,
    });
  }

  const methodName = rawId ? sanitizeMethodName(rawId) : fallbackMethodName(group, method, path);
  if (rawId && methodName !== rawId) {
    issues.push({
      escalates: false,
      message: `Operation ${method.toUpperCase()} ${path} uses the reserved name "${rawId}"; the method was renamed to "${methodName}".`,
      operationId: rawId,
      method,
      path,
    });
  }
  const methodKey = `${group}.${methodName}`;
  const collision = byMethodKey.get(methodKey);
  if (collision) {
    throw new ClientGenerationError(
      `Duplicate method "${methodKey}" produced by ${collision.method.toUpperCase()} ${collision.path} and ${method.toUpperCase()} ${path}. Rename one operationId or tag.`
    );
  }
  byMethodKey.set(methodKey, { method, path });

  const { properties: parameters, dropped } = collectParameters(document, operation);
  if (dropped.length > 0) {
    issues.push({
      escalates: false,
      message: `Operation ${method.toUpperCase()} ${path} has duplicate parameter name(s) ${dropped.join(', ')}; the path or query parameter wins over the body property.`,
      ...(rawId ? { operationId: rawId } : {}),
      method,
      path,
    });
  }
  const envelope = operation['x-blend-envelope'] ?? 'data';
  const result = resolveResult(operation, group, methodName, envelope);
  if (result.untyped) {
    issues.push({
      escalates: true,
      message: `Operation ${method.toUpperCase()} ${path} has no 2xx response schema; its result type is unknown.`,
      ...(rawId ? { operationId: rawId } : {}),
      method,
      path,
    });
  }

  operations.push({
    operationId: rawId ?? methodName,
    methodName,
    method,
    path,
    group,
    envelope,
    untypedResponse: result.untyped,
    parameters,
    resultType: result.type,
    ...(result.name ? { resultTypeName: result.name } : {}),
    ...(result.definition ? { resultTypeDefinition: result.definition } : {}),
    ...(parameters.length > 0
      ? { paramsTypeName: typeAliasName(group, methodName, 'Params') }
      : {}),
  });
}

/**
 * Builds a sanitized, deterministic TypeScript alias name.
 *
 * @param group - The operation group.
 * @param methodName - The resolved method name.
 * @param suffix - The alias suffix, for example `Params` or `Result`.
 * @returns A valid, unique type alias identifier.
 */
function typeAliasName(group: string, methodName: string, suffix: string): string {
  return sanitizeIdentifier(`${pascalCase(group)}${pascalCase(methodName)}${suffix}`);
}

/**
 * Collects the flat params properties for one operation: path parameters,
 * query parameters, and the JSON request body.
 *
 * A `$ref` body that resolves to an object is flattened into the params object,
 * mirroring the server's merged validation object. Any other body becomes a
 * single `body` property. Header and cookie parameters are ignored because the
 * runtime owns those.
 *
 * @param document - The OpenAPI document, for resolving body references.
 * @param operation - The OpenAPI operation.
 * @returns The params properties and any body property names dropped as duplicates.
 */
function collectParameters(
  document: OpenAPIDocument,
  operation: OpenAPIOperation
): { properties: ParamProperty[]; dropped: string[] } {
  const properties: ParamProperty[] = [];
  const dropped: string[] = [];
  const names = new Set<string>();
  const add = (property: ParamProperty): void => {
    if (names.has(property.name)) {
      dropped.push(property.name);
      return;
    }
    names.add(property.name);
    properties.push(property);
  };

  for (const parameter of operation.parameters ?? []) {
    if (parameter.in === 'path') {
      add({ name: parameter.name, type: schemaToType(parameter.schema), required: true });
    } else if (parameter.in === 'query') {
      add({
        name: parameter.name,
        type: schemaToType(parameter.schema),
        required: parameter.required === true,
      });
    }
  }

  const body = operation.requestBody?.content?.['application/json']?.schema;
  if (body) {
    const resolved = resolveObjectSchema(document, body);
    if (resolved?.properties && Object.keys(resolved.properties).length > 0) {
      const required = new Set(resolved.required ?? []);
      for (const [name, schema] of Object.entries(resolved.properties)) {
        add({ name, type: schemaToType(schema), required: required.has(name) });
      }
    } else {
      add({
        name: 'body',
        type: schemaToType(body),
        required: operation.requestBody?.required === true,
      });
    }
  }
  return { properties, dropped };
}

/**
 * Resolves the JSON schema of the first 2xx response that has one.
 *
 * @param operation - The OpenAPI operation.
 * @returns The response schema, or undefined when none exists.
 */
function successSchema(operation: OpenAPIOperation): OpenAPISchema | undefined {
  const responses = operation.responses ?? {};
  const statuses = Object.keys(responses)
    .map(status => Number(status))
    .filter(status => Number.isInteger(status) && status >= 200 && status < 300)
    .sort((left, right) => left - right);
  for (const status of statuses) {
    const schema = responses[String(status)]?.content?.['application/json']?.schema;
    if (schema) {
      return schema;
    }
  }
  return undefined;
}

/**
 * Resolves the result type for one operation.
 *
 * A `$ref` in a `data` envelope uses the component type directly. An inline
 * schema gets a named `<Operation>Result` alias. A missing schema is `unknown`.
 * A `body` envelope wraps the inner type in `PaginatedResponse`.
 *
 * @param operation - The OpenAPI operation.
 * @param methodName - The resolved method name, used for the alias.
 * @param envelope - The operation's response envelope.
 * @returns The result type, its optional alias name, and the untyped flag.
 */
function resolveResult(
  operation: OpenAPIOperation,
  group: string,
  methodName: string,
  envelope: 'data' | 'body'
): { type: string; name?: string; definition?: string; untyped: boolean } {
  const alias = typeAliasName(group, methodName, 'Result');
  const schema = successSchema(operation);
  if (envelope === 'body') {
    const inner = schema ? schemaToType(schema) : 'unknown';
    return {
      type: alias,
      name: alias,
      definition: `PaginatedResponse<${inner}>`,
      untyped: !schema,
    };
  }
  if (!schema) {
    return { type: 'unknown', untyped: true };
  }
  if (schema.$ref) {
    return { type: defaultResolveReference(schema.$ref), untyped: false };
  }
  return { type: alias, name: alias, definition: schemaToType(schema), untyped: false };
}

/**
 * Resolves a body schema that may be a reference to a component object.
 *
 * @param document - The OpenAPI document.
 * @param schema - The body schema, possibly a `$ref`.
 * @returns The resolved object schema, or undefined when it is not an object.
 */
function resolveObjectSchema(
  document: OpenAPIDocument,
  schema: OpenAPISchema
): OpenAPISchema | undefined {
  if (!schema.$ref) {
    return schema.type === 'object' || schema.properties ? schema : undefined;
  }
  const rawName = schema.$ref.split('/').pop() ?? '';
  const resolved = document.components?.schemas?.[rawName];
  if (resolved && (resolved.type === 'object' || resolved.properties)) {
    return resolved;
  }
  return undefined;
}

/**
 * Converts pending issues into public issues at the requested strictness.
 *
 * @param pending - The collected issues.
 * @param escalate - When true, escalating issues become errors.
 * @returns The public issues.
 */
function finalizeIssues(pending: PendingIssue[], escalate: boolean): ContractIssue[] {
  return pending.map(issue => ({
    severity: escalate && issue.escalates ? 'error' : 'warning',
    message: issue.message,
    ...(issue.operationId ? { operationId: issue.operationId } : {}),
    method: issue.method,
    path: issue.path,
  }));
}

/**
 * Builds the full set of generated files in memory, before formatting.
 *
 * @param document - The OpenAPI document.
 * @param operations - The resolved operations.
 * @param runtimeImport - The runtime import specifier.
 * @param options - The generator options.
 * @returns A map of file name to unformatted content.
 */
function emitFiles(
  document: OpenAPIDocument,
  operations: OperationModel[],
  runtimeImport: string,
  options: ClientGeneratorOptions
): Map<string, string> {
  const files = new Map<string, string>();
  const clientName = sanitizeIdentifier(options.clientName ?? 'AppClient');
  files.set('types.ts', emitTypesFile(document, operations, runtimeImport));

  if (options.splitByGroup) {
    const groups = groupOperations(operations);
    for (const [group, groupOperations] of groups) {
      files.set(`client.${group}.ts`, emitGroupFile(group, groupOperations, runtimeImport));
    }
    files.set('client.ts', emitBarrelFile(runtimeImport, [...groups.keys()], clientName));
  } else {
    files.set('client.ts', emitClientFile(operations, runtimeImport, clientName));
  }
  files.set('index.ts', emitIndexFile());
  return files;
}

/**
 * Emits `types.ts`: component aliases plus per-operation params and result
 * aliases, each sorted for stable output.
 *
 * @param document - The OpenAPI document, for component schemas.
 * @param operations - The resolved operations.
 * @param runtimeImport - The runtime import specifier.
 * @returns The unformatted file content.
 */
function emitTypesFile(
  document: OpenAPIDocument,
  operations: OperationModel[],
  runtimeImport: string
): string {
  const lines: string[] = [GENERATED_MARKER];
  const needsPaginated = operations.some(operation => operation.envelope === 'body');
  if (needsPaginated) {
    lines.push('', `import type { PaginatedResponse } from ${JSON.stringify(runtimeImport)};`);
  }

  const components = Object.entries(document.components?.schemas ?? {}).sort(([left], [right]) =>
    left.localeCompare(right)
  );
  for (const [name, schema] of components) {
    lines.push('', `export type ${componentTypeName(name)} = ${schemaToType(schema)};`);
  }

  for (const operation of operations) {
    if (operation.paramsTypeName) {
      lines.push('', `export type ${operation.paramsTypeName} = ${paramsType(operation)};`);
    }
    if (operation.resultTypeName) {
      const definition = operation.resultTypeDefinition ?? 'unknown';
      lines.push('', `export type ${operation.resultTypeName} = ${definition};`);
    }
  }
  return `${lines.join('\n')}\n`;
}

/**
 * Renders the params object type for one operation.
 *
 * @param operation - The resolved operation.
 * @returns An inline object type expression.
 */
function paramsType(operation: OperationModel): string {
  const members = operation.parameters.map(
    parameter =>
      `${propertyName(parameter.name)}${parameter.required ? '' : '?'}: ${parameter.type};`
  );
  return `{ ${members.join(' ')} }`;
}

/**
 * Emits the single-file `client.ts`.
 *
 * @param operations - The resolved operations.
 * @param runtimeImport - The runtime import specifier.
 * @param clientName - The generated client type name.
 * @returns The unformatted file content.
 */
function emitClientFile(
  operations: OperationModel[],
  runtimeImport: string,
  clientName: string
): string {
  const typeImports = collectLocalTypeNames(operations);
  const lines: string[] = [GENERATED_MARKER, '', runtimeImportLine(runtimeImport, false)];
  if (typeImports.length > 0) {
    lines.push(`import type { ${typeImports.join(', ')} } from './types.js';`);
  }

  const groups = groupOperations(operations);
  lines.push('', `export interface ${clientName} {`);
  for (const [group, groupOperations] of groups) {
    lines.push(`  ${group}: {`);
    for (const operation of groupOperations) {
      lines.push(`    ${methodSignature(operation)};`);
    }
    lines.push('  };');
  }
  lines.push(
    '}',
    '',
    `export function create${clientName}(options: ApiClientOptions): ${clientName} {`
  );
  lines.push('  const runtime = createApiClient(options);', '  return {');
  for (const [group, groupOperations] of groups) {
    lines.push(`    ${group}: {`);
    for (const operation of groupOperations) {
      lines.push(`      ${methodCall(operation)}`);
    }
    lines.push('    },');
  }
  lines.push('  };', '}');
  return `${lines.join('\n')}\n`;
}

/**
 * Emits one `client.<group>.ts` file for `splitByGroup`.
 *
 * @param group - The group name.
 * @param operations - The group's operations.
 * @param runtimeImport - The runtime import specifier.
 * @returns The unformatted file content.
 */
function emitGroupFile(group: string, operations: OperationModel[], runtimeImport: string): string {
  const interfaceName = `${capitalize(group)}Client`;
  const factoryName = `create${interfaceName}`;
  const typeImports = collectLocalTypeNames(operations);
  const lines: string[] = [GENERATED_MARKER, '', runtimeImportLine(runtimeImport, true)];
  if (typeImports.length > 0) {
    lines.push(`import type { ${typeImports.join(', ')} } from './types.js';`);
  }

  lines.push('', `export interface ${interfaceName} {`);
  for (const operation of operations) {
    lines.push(`  ${methodSignature(operation)};`);
  }
  lines.push('}', '', `export function ${factoryName}(runtime: RuntimeClient): ${interfaceName} {`);
  lines.push('  return {');
  for (const operation of operations) {
    lines.push(`    ${methodCall(operation)}`);
  }
  lines.push('  };', '}');
  return `${lines.join('\n')}\n`;
}

/**
 * Emits the `client.ts` barrel used with `splitByGroup`.
 *
 * @param runtimeImport - The runtime import specifier.
 * @param groups - The group names, in stable order.
 * @param clientName - The generated client type name.
 * @returns The unformatted file content.
 */
function emitBarrelFile(runtimeImport: string, groups: string[], clientName: string): string {
  const lines: string[] = [
    GENERATED_MARKER,
    '',
    `import { createApiClient, type ApiClientOptions } from ${JSON.stringify(runtimeImport)};`,
  ];
  for (const group of groups) {
    const interfaceName = `${capitalize(group)}Client`;
    lines.push(
      `import { create${interfaceName}, type ${interfaceName} } from './client.${group}.js';`
    );
  }
  lines.push('', `export interface ${clientName} {`);
  for (const group of groups) {
    lines.push(`  ${group}: ${capitalize(group)}Client;`);
  }
  lines.push(
    '}',
    '',
    `export function create${clientName}(options: ApiClientOptions): ${clientName} {`
  );
  lines.push('  const runtime = createApiClient(options);', '  return {');
  for (const group of groups) {
    lines.push(`    ${group}: create${capitalize(group)}Client(runtime),`);
  }
  lines.push('  };', '}');
  return `${lines.join('\n')}\n`;
}

/**
 * Emits the `index.ts` barrel.
 *
 * @returns The unformatted file content.
 */
function emitIndexFile(): string {
  return `${GENERATED_MARKER}\n\nexport * from './types.js';\nexport * from './client.js';\n`;
}

/**
 * Builds the runtime import line used by generated client files.
 *
 * @param runtimeImport - The runtime import specifier.
 * @param includeRuntimeClient - Whether to import the `RuntimeClient` type.
 * @returns The import statement.
 */
function runtimeImportLine(runtimeImport: string, includeRuntimeClient: boolean): string {
  const names = [
    'createApiClient',
    'type ApiClientOptions',
    'type OperationDescriptor',
    'type RequestOptions',
  ];
  if (includeRuntimeClient) {
    names.push('type RuntimeClient');
  }
  return `import { ${names.join(', ')} } from ${JSON.stringify(runtimeImport)};`;
}

/**
 * Renders one method signature for a group interface.
 *
 * @param operation - The resolved operation.
 * @returns The method signature text.
 */
function methodSignature(operation: OperationModel): string {
  const params = operation.paramsTypeName
    ? `params: ${operation.paramsTypeName}, options?: RequestOptions`
    : 'options?: RequestOptions';
  return `${operation.methodName}: (${params}) => Promise<${operation.resultType}>`;
}

/**
 * Renders one method implementation for a group object.
 *
 * @param operation - The resolved operation.
 * @returns The method implementation text.
 */
function methodCall(operation: OperationModel): string {
  const params = operation.paramsTypeName ? 'params' : '{}';
  const signature = operation.paramsTypeName ? 'params, options' : 'options';
  return `${operation.methodName}: (${signature}) => runtime.request<${operation.resultType}>(${descriptor(operation)}, ${params}, options),`;
}

/**
 * Renders the operation descriptor for one operation.
 *
 * @param operation - The resolved operation.
 * @returns The descriptor expression.
 */
function descriptor(operation: OperationModel): string {
  const method = JSON.stringify(operation.method);
  const path = JSON.stringify(operation.path);
  const envelope = JSON.stringify(operation.envelope);
  const operationId = JSON.stringify(operation.operationId);
  return `{ method: ${method}, path: ${path}, envelope: ${envelope}, operationId: ${operationId} } satisfies OperationDescriptor`;
}

/**
 * Groups operations by their client group, in stable order.
 *
 * @param operations - The resolved operations.
 * @returns The operations grouped and sorted by group name.
 */
function groupOperations(operations: OperationModel[]): Map<string, OperationModel[]> {
  const groups = new Map<string, OperationModel[]>();
  for (const operation of [...operations].sort(compareOperations)) {
    const list = groups.get(operation.group) ?? [];
    list.push(operation);
    groups.set(operation.group, list);
  }
  return new Map([...groups.entries()].sort(([left], [right]) => left.localeCompare(right)));
}

/**
 * Orders operations deterministically by group, then method name.
 *
 * @param left - The first operation.
 * @param right - The second operation.
 * @returns A negative, zero, or positive comparison.
 */
function compareOperations(left: OperationModel, right: OperationModel): number {
  const byGroup = left.group.localeCompare(right.group);
  return byGroup !== 0 ? byGroup : left.methodName.localeCompare(right.methodName);
}

/**
 * Collects the `./types.js` names referenced by one or more operations.
 *
 * @param operations - The operations to inspect.
 * @returns The sorted, unique type names.
 */
function collectLocalTypeNames(operations: readonly OperationModel[]): string[] {
  const names = new Set<string>();
  for (const operation of operations) {
    if (operation.paramsTypeName) {
      names.add(operation.paramsTypeName);
    }
    if (operation.resultTypeName) {
      names.add(operation.resultTypeName);
    }
    if (!operation.resultTypeName && operation.resultType !== 'unknown') {
      names.add(operation.resultType);
    }
  }
  return [...names].sort();
}

/**
 * Writes a property name, quoting it when it is not a valid identifier.
 *
 * @param name - The raw property name.
 * @returns An identifier or a quoted string.
 */
function propertyName(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(name) ? name : JSON.stringify(name);
}

/**
 * Capitalizes the first character of a group name.
 *
 * @param value - The group name.
 * @returns The capitalized name.
 */
function capitalize(value: string): string {
  return value.length === 0 ? value : value.charAt(0).toUpperCase() + value.slice(1);
}

/**
 * Formats every generated file with Prettier.
 *
 * @param files - The unformatted files.
 * @returns The formatted files, keyed by name.
 */
async function formatFiles(files: Map<string, string>): Promise<Map<string, string>> {
  const formatted = new Map<string, string>();
  for (const [name, content] of files) {
    const parser: Options['parser'] = extname(name) === '.json' ? 'json' : 'typescript';
    formatted.set(name, await format(content, { ...PRETTIER_OPTIONS, parser }));
  }
  return formatted;
}

/**
 * Deletes marker-bearing files in an output directory that are no longer
 * generated. Files without the marker are left untouched.
 *
 * @param directory - The output directory.
 * @param keep - The file names that remain.
 */
async function pruneStaleFiles(directory: string, keep: Set<string>): Promise<void> {
  for (const name of await listMarkerFiles(directory)) {
    if (!keep.has(name)) {
      await rm(join(directory, name));
    }
  }
}

/**
 * Lists the files in a directory that start with the generated marker.
 *
 * @param directory - The output directory.
 * @returns The marker-bearing file names.
 */
async function listMarkerFiles(directory: string): Promise<string[]> {
  let entries: Dirent[];
  try {
    entries = await readdir(directory, { withFileTypes: true });
  } catch {
    return [];
  }
  const marked: string[] = [];
  for (const entry of entries) {
    // Only regular files are generated; skip directories, symlinks, and special
    // files (a FIFO read would block).
    if (!entry.isFile()) {
      continue;
    }
    const content = await readIfExists(join(directory, entry.name));
    if (content !== undefined && content.startsWith(GENERATED_MARKER)) {
      marked.push(entry.name);
    }
  }
  return marked;
}

/**
 * Reads a file when it exists.
 *
 * @param path - The file path.
 * @returns The file content, or undefined when it does not exist.
 */
async function readIfExists(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, 'utf8');
  } catch {
    return undefined;
  }
}
